### ISSUE TITLE
License Checklist

### ISSUE THREAD

**Issue by roanraina** [UBC-MDS/twitter-persona#40]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed.

**Comment by RenzoWijn** [comment]
Our current license is the MIT License: a very common, short, and simple permissive license that only requires the preservation of copyright and license notices for users. It comes with a lot of flexibility, which is convenient for the development of a package.

Other popular licenses that we'll discuss in order to find the one that works best for us are:

- GNU GPLv3
- Apache License 2.0
- Boost Software License 1.0

All of the licenses above require the preservation of copyright and license notices for the source code.

The GPLv3 License provides a lot of freedom to anyone wanting to use our package, just like the MIT license does. However, it does require anyone using our package in their software to use the same license and to keep track of the source code and any modifications. To provide the most freedom for anyone wanting to use our package, I'd recommend using the MIT license over GPLv3.

The Apache license is a lot less easy to understand for the general public, and contains a lot more legal jargon. This would decrease accessibility to our package for people relatively new to coding (like we effectively are), and also specifically states it does not grant trademark rights. Therefore I don't think it's the right fit for our package.

The Boost Software License 1.0 is in simple terms a narrower version of the MIT license: it states everything a user is permitted to do instead of just covering it with a "deal in the Software without restriction" clause. Another major difference is that users do not need to include a copy of the boost license in an executable binary, while this is required under the MIT license.

Therefore I think MIT is the broadest, easy to use but legally covering license we can use for our package, and since it is also used by most packages that our package uses (wordcloud, dplyr).

References:
[1]: https://choosealicense.com/licenses/
[2]: https://pypi.org/project/wordcloud/
[3]: https://dplyr.tidyverse.org/LICENSE.html

**Comment by Yurui-Feng** [comment]
Using an MIT license for our package makes sense since it is an open-source license that places minimum limits on the use, modification, and distribution of our work.  In addition, by choosing an MIT license, we retain ownership of our code's intellectual property while enabling others to utilize it. This is especially important because we incorporate NLP models from other libraries into our package, as some models may be proprietary and subject to additional restrictions.

**Comment by tiger12055** [comment]
Agree with Yurui
